In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('chicago-traffic-tracker-historical-congestion-estimates-by-segment-2018-current-1.csv', index_col='TIME', parse_dates=True)
df.head()

SEGMENT_ID  SPEED  STREET DIRECTION          FROM_STREET  \
TIME                                                                            
2018-03-21 17:31:00        1133     23  Cicero        SB               Cermak   
2018-03-21 17:31:00        1134     20  Cicero        SB            Roosevelt   
2018-03-21 17:31:00        1151     20  Harlem        NB              Madison   
2018-03-21 17:31:00        1152     23  Harlem        NB              Chicago   
2018-03-21 17:31:00        1153     14  Harlem        NB  Forest Preserve Ave   

                     TO_STREET  LENGTH STREET_HEADING             COMMENTS  \
TIME                                                                         
2018-03-21 17:31:00       31st    1.00              S  Outside City Limits   
2018-03-21 17:31:00     Cermak    1.02              S  Outside City Limits   
2018-03-21 17:31:00    Chicago    1.01              S  Outside City Limits   
2018-03-21 17:31:00  North Ave    1.01              N  Outside City Limits   
2018-03-21 17:31:00   Gunnison    1.00              N  Outside City Limits   

                     BUS_COUNT  ...          RECORD_ID  START_LATITUDE  \
TIME                            ...                                      
2018-03-21 17:31:00          3  ...  1133-201803212231       41.851245   
2018-03-21 17:31:00          2  ...  1134-201803212231       41.865963   
2018-03-21 17:31:00          1  ...  1151-201803212231       41.879699   
2018-03-21 17:31:00          1  ...  1152-201803212231       41.894268   
2018-03-21 17:31:00          3  ...  1153-201803212231       41.953814   

                     START_LONGITUDE  END_LATITUDE END_LONGITUDE  \
TIME                                                               
2018-03-21 17:31:00       -87.744434     41.836747    -87.743932   
2018-03-21 17:31:00       -87.744985     41.851245    -87.744434   
2018-03-21 17:31:00       -87.804549     41.894268    -87.805101   
2018-03-21 17:31:00       -87.805101     41.908856    -87.805554   
2018-03-21 17:31:00       -87.807150     41.968344    -87.806982   

                                           START_LOCATION  \
TIME                                                        
2018-03-21 17:31:00  POINT (-87.7444337191 41.8512451897)   
2018-03-21 17:31:00  POINT (-87.7449852043 41.8659627382)   
2018-03-21 17:31:00  POINT (-87.8045488066 41.8796992839)   
2018-03-21 17:31:00  POINT (-87.8051007941 41.8942683013)   
2018-03-21 17:31:00  POINT (-87.8071497455 41.9538138239)   

                                             END_LOCATION  Community Areas  \
TIME                                                                         
2018-03-21 17:31:00  POINT (-87.7439318058 41.8367473974)              NaN   
2018-03-21 17:31:00  POINT (-87.7444337191 41.8512451897)             26.0   
2018-03-21 17:31:00  POINT (-87.8051007941 41.8942683013)              NaN   
2018-03-21 17:31:00  POINT (-87.8055536529 41.9088560337)              NaN   
2018-03-21 17:31:00  POINT (-87.8069823878 41.9683436725)             17.0   

                     Zip Codes Wards  
TIME                                  
2018-03-21 17:31:00       4458   NaN  
2018-03-21 17:31:00      22216   7.0  
2018-03-21 17:31:00      26615   NaN  
2018-03-21 17:31:00      26615   NaN  
2018-03-21 17:31:00      22254  19.0  

[5 rows x 24 columns]

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df.describe()

SEGMENT_ID         SPEED        LENGTH     BUS_COUNT  MESSAGE_COUNT  \
count  1.048575e+06  1.048575e+06  1.048575e+06  1.048575e+06   1.048575e+06   
mean   5.952952e+02  1.400872e+01  5.272278e-01  1.070417e+00   6.071268e+00   
std    3.795893e+02  1.360243e+01  1.820631e-01  1.495457e+00   1.012439e+01   
min    1.000000e+00 -1.000000e+00  7.000000e-02  0.000000e+00   0.000000e+00   
25%    2.710000e+02 -1.000000e+00  5.000000e-01  0.000000e+00   0.000000e+00   
50%    5.490000e+02  1.700000e+01  5.000000e-01  1.000000e+00   3.000000e+00   
75%    8.900000e+02  2.500000e+01  5.300000e-01  1.000000e+00   9.000000e+00   
max    1.309000e+03  5.700000e+01  1.540000e+00  3.400000e+01   3.910000e+02   

               HOUR   DAY_OF_WEEK      MONTH  START_LATITUDE  START_LONGITUDE  \
count  1.048575e+06  1.048575e+06  1048575.0    1.048575e+06     1.048575e+06   
mean   1.151124e+01  3.993011e+00        3.0    4.184994e+01    -8.768073e+01   
std    6.844329e+00  1.970562e+00        0.0    8.563725e-02     5.870863e-02   
min    0.000000e+00  1.000000e+00        3.0    4.165897e+01    -8.783677e+01   
25%    6.000000e+00  2.000000e+00        3.0    4.178594e+01    -8.772486e+01   
50%    1.200000e+01  4.000000e+00        3.0    4.185991e+01    -8.766907e+01   
75%    1.700000e+01  6.000000e+00        3.0    4.191063e+01    -8.763563e+01   
max    2.300000e+01  7.000000e+00        3.0    4.201283e+01    -8.753505e+01   

       END_LATITUDE  END_LONGITUDE  Community Areas     Zip Codes  \
count  1.048575e+06   1.048575e+06    983474.000000  1.048575e+06   
mean   4.185000e+01  -8.768074e+01        40.357718  1.795353e+04   
std    8.567375e-02   5.872085e-02        20.049761  6.388836e+03   
min    4.165901e+01  -8.783683e+01         1.000000  2.733000e+03   
25%    4.178594e+01  -8.772485e+01        25.000000  1.492000e+04   
50%    4.185991e+01  -8.766905e+01        37.000000  2.154600e+04   
75%    4.191063e+01  -8.763526e+01        58.000000  2.224800e+04   
max    4.201283e+01  -8.753505e+01        77.000000  2.662400e+04   

              Wards  
count  983474.00000  
mean       26.12412  
std        14.83736  
min         1.00000  
25%        12.00000  
50%        28.00000  
75%        38.00000  
max        50.00000

In [11]:
print(df.dtypes)

SEGMENT_ID           int64
SPEED                int64
STREET              object
DIRECTION           object
FROM_STREET         object
TO_STREET           object
LENGTH             float64
STREET_HEADING      object
COMMENTS            object
BUS_COUNT            int64
MESSAGE_COUNT        int64
HOUR                 int64
DAY_OF_WEEK          int64
MONTH                int64
RECORD_ID           object
START_LATITUDE     float64
START_LONGITUDE    float64
END_LATITUDE       float64
END_LONGITUDE      float64
START_LOCATION      object
END_LOCATION        object
Community Areas    float64
Zip Codes            int64
Wards              float64
dtype: object


In [12]:
df.index

DatetimeIndex(['2018-03-21 17:31:00', '2018-03-21 17:31:00',
               '2018-03-21 17:31:00', '2018-03-21 17:31:00',
               '2018-03-21 17:31:00', '2018-03-21 17:31:00',
               '2018-03-21 17:31:00', '2018-03-21 17:31:00',
               '2018-03-21 17:31:00', '2018-03-21 17:31:00',
               ...
               '2018-03-14 13:10:00', '2018-03-14 13:10:00',
               '2018-03-14 13:10:00', '2018-03-14 13:10:00',
               '2018-03-14 13:10:00', '2018-03-14 13:10:00',
               '2018-03-14 13:10:00', '2018-03-14 13:10:00',
               '2018-03-14 13:10:00', '2018-03-14 13:10:00'],
              dtype='datetime64[ns]', name='TIME', length=1048575, freq=None)

In [13]:
df['STREET'].unique()

array(['Cicero', 'Harlem', 'Halsted', 'Jackson', 'Balbo', 'Harrison',
       'Clark', 'Pershing', 'Indiana', '57th', 'Broadway', 'Sheridan',
       'Dr Martin L King Jr', 'State', 'LaSalle', 'Chicago', 'Columbus',
       'Archer', 'Torrence', 'Touhy', '111th', 'Randolph', 'Washington',
       '127th', '130th', 'Cermak', 'Ohio', 'Ontario', 'Lake Shore Dr',
       'Milwaukee', 'Higgins', 'Illinois', 'Jefferson', 'Stony Island',
       'Peterson', 'Ridge', 'Hollywood', 'Warren', 'Ewing', 'Grand',
       'Wacker', 'Michigan', 'Madison', 'Caldwell', '55th', 'Monterey',
       '95th', 'Elston', 'Congress', 'Cumberland', 'Ramp To Cermak Rd',
       'Desplaines', 'Irving Park', '87th', 'Pulaski', 'North', 'Western',
       'Roosevelt', '79th', 'Fairbanks', 'Ashland', 'Garfield'],
      dtype=object)

In [14]:
df['DIRECTION'].unique()

array(['SB', 'NB', 'EB', 'WB', 'NE', 'NW', 'SE', 'SW'], dtype=object)

In [15]:
df['DAY_OF_WEEK'].unique()

array([4, 3, 2, 1, 7, 6, 5], dtype=int64)

In [19]:
df['HOUR'].unique()

array([17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,
        0, 23, 22, 21, 20, 19, 18], dtype=int64)

In [17]:
df['DAY_OF_WEEK']=df['DAY_OF_WEEK'].astype('category',copy=False)

In [18]:
df['DAY_OF_WEEK'].unique()

[4, 3, 2, 1, 7, 6, 5]
Categories (7, int64): [4, 3, 2, 1, 7, 6, 5]

In [20]:
df['HOUR']=df['HOUR'].astype('category',copy=False)

In [21]:
df['HOUR'].unique()

[17, 16, 15, 14, 13, ..., 22, 21, 20, 19, 18]
Length: 24
Categories (24, int64): [17, 16, 15, 14, ..., 21, 20, 19, 18]

In [22]:
df['MONTH']=df['MONTH'].astype('category',copy=False)

In [23]:
df['MONTH'].unique()

[3]
Categories (1, int64): [3]

In [24]:
df.drop('MONTH', axis=1, inplace=True)

In [25]:
df.head()

SEGMENT_ID  SPEED  STREET DIRECTION          FROM_STREET  \
TIME                                                                            
2018-03-21 17:31:00        1133     23  Cicero        SB               Cermak   
2018-03-21 17:31:00        1134     20  Cicero        SB            Roosevelt   
2018-03-21 17:31:00        1151     20  Harlem        NB              Madison   
2018-03-21 17:31:00        1152     23  Harlem        NB              Chicago   
2018-03-21 17:31:00        1153     14  Harlem        NB  Forest Preserve Ave   

                     TO_STREET  LENGTH STREET_HEADING             COMMENTS  \
TIME                                                                         
2018-03-21 17:31:00       31st    1.00              S  Outside City Limits   
2018-03-21 17:31:00     Cermak    1.02              S  Outside City Limits   
2018-03-21 17:31:00    Chicago    1.01              S  Outside City Limits   
2018-03-21 17:31:00  North Ave    1.01              N  Outside City Limits   
2018-03-21 17:31:00   Gunnison    1.00              N  Outside City Limits   

                     BUS_COUNT  ...          RECORD_ID START_LATITUDE  \
TIME                            ...                                     
2018-03-21 17:31:00          3  ...  1133-201803212231      41.851245   
2018-03-21 17:31:00          2  ...  1134-201803212231      41.865963   
2018-03-21 17:31:00          1  ...  1151-201803212231      41.879699   
2018-03-21 17:31:00          1  ...  1152-201803212231      41.894268   
2018-03-21 17:31:00          3  ...  1153-201803212231      41.953814   

                    START_LONGITUDE END_LATITUDE  END_LONGITUDE  \
TIME                                                              
2018-03-21 17:31:00      -87.744434    41.836747     -87.743932   
2018-03-21 17:31:00      -87.744985    41.851245     -87.744434   
2018-03-21 17:31:00      -87.804549    41.894268     -87.805101   
2018-03-21 17:31:00      -87.805101    41.908856     -87.805554   
2018-03-21 17:31:00      -87.807150    41.968344     -87.806982   

                                           START_LOCATION  \
TIME                                                        
2018-03-21 17:31:00  POINT (-87.7444337191 41.8512451897)   
2018-03-21 17:31:00  POINT (-87.7449852043 41.8659627382)   
2018-03-21 17:31:00  POINT (-87.8045488066 41.8796992839)   
2018-03-21 17:31:00  POINT (-87.8051007941 41.8942683013)   
2018-03-21 17:31:00  POINT (-87.8071497455 41.9538138239)   

                                             END_LOCATION  Community Areas  \
TIME                                                                         
2018-03-21 17:31:00  POINT (-87.7439318058 41.8367473974)              NaN   
2018-03-21 17:31:00  POINT (-87.7444337191 41.8512451897)             26.0   
2018-03-21 17:31:00  POINT (-87.8051007941 41.8942683013)              NaN   
2018-03-21 17:31:00  POINT (-87.8055536529 41.9088560337)              NaN   
2018-03-21 17:31:00  POINT (-87.8069823878 41.9683436725)             17.0   

                    Zip Codes Wards  
TIME                                 
2018-03-21 17:31:00      4458   NaN  
2018-03-21 17:31:00     22216   7.0  
2018-03-21 17:31:00     26615   NaN  
2018-03-21 17:31:00     26615   NaN  
2018-03-21 17:31:00     22254  19.0  

[5 rows x 23 columns]

In [26]:
print(df.dtypes)

SEGMENT_ID            int64
SPEED                 int64
STREET               object
DIRECTION            object
FROM_STREET          object
TO_STREET            object
LENGTH              float64
STREET_HEADING       object
COMMENTS             object
BUS_COUNT             int64
MESSAGE_COUNT         int64
HOUR               category
DAY_OF_WEEK        category
RECORD_ID            object
START_LATITUDE      float64
START_LONGITUDE     float64
END_LATITUDE        float64
END_LONGITUDE       float64
START_LOCATION       object
END_LOCATION         object
Community Areas     float64
Zip Codes             int64
Wards               float64
dtype: object


In [27]:
df['SEGMENT_ID'].unique()

array([1133, 1134, 1151, ...,  139,  140,  141], dtype=int64)

In [28]:
df['SEGMENT_ID'].count()

1048575

In [30]:
df.drop('SEGMENT_ID', axis=1, inplace=True)

KeyError: "['SEGMENT_ID'] not found in axis"

In [31]:
df['DIRECTION']=df['DIRECTION'].astype('category',copy=False)

In [32]:
df['FROM_STREET'].unique()

array(['Cermak', 'Roosevelt', 'Madison', 'Chicago', 'Forest Preserve Ave',
       '51st', '47th', '43rd', 'Pershing', '35th', '31st', 'Archer',
       '16th', 'Halsted', 'LakeShore Dr', 'State', 'Harrison', 'Canal',
       'Damen', 'Ashland', 'North Ave', 'Gunnison', '130th',
       'Stony Island', 'Lake Shore Dr', 'Hollywood', 'Devon', 'Pratt',
       'Touhy', 'Ridge', '24th', 'Diversey', 'Belmont', 'Addison',
       'Irving Park', '127th', 'Congress', 'Wacker', 'Jackson', 'Grand',
       'Division', 'Armitage', 'Fullerton', 'Michigan', 'LaSalle',
       'Milwaukee', '107th', '103rd', '99th', '95th', '91st', '87th',
       '83rd', '79th', '76th', '71st', '67th', '63rd', '59th', '55th',
       'Randolph', 'Narragansett', 'Austin', 'Central', 'Laramie',
       'Dan Ryan Expy', 'Dr Martin L King Jr', 'Cottage Grove', 'Oriole',
       'Caldwell', 'Crawford', 'Kedzie', 'Western', 'Racine', '1550 West',
       'Indiana', 'I-94 Expy', 'Torrence', 'Harlem', 'Ridgeland',
       'Cicero', 'City

In [33]:
df['FROM_STREET']=df['FROM_STREET'].astype('category',copy=False)


In [34]:
df['TO_STREET']=df['TO_STREET'].astype('category',copy=False)

In [35]:
df.head()

SPEED  STREET DIRECTION          FROM_STREET  TO_STREET  \
TIME                                                                           
2018-03-21 17:31:00     23  Cicero        SB               Cermak       31st   
2018-03-21 17:31:00     20  Cicero        SB            Roosevelt     Cermak   
2018-03-21 17:31:00     20  Harlem        NB              Madison    Chicago   
2018-03-21 17:31:00     23  Harlem        NB              Chicago  North Ave   
2018-03-21 17:31:00     14  Harlem        NB  Forest Preserve Ave   Gunnison   

                     LENGTH STREET_HEADING             COMMENTS  BUS_COUNT  \
TIME                                                                         
2018-03-21 17:31:00    1.00              S  Outside City Limits          3   
2018-03-21 17:31:00    1.02              S  Outside City Limits          2   
2018-03-21 17:31:00    1.01              S  Outside City Limits          1   
2018-03-21 17:31:00    1.01              N  Outside City Limits          1   
2018-03-21 17:31:00    1.00              N  Outside City Limits          3   

                     MESSAGE_COUNT  ...          RECORD_ID START_LATITUDE  \
TIME                                ...                                     
2018-03-21 17:31:00             17  ...  1133-201803212231      41.851245   
2018-03-21 17:31:00             24  ...  1134-201803212231      41.865963   
2018-03-21 17:31:00              5  ...  1151-201803212231      41.879699   
2018-03-21 17:31:00             15  ...  1152-201803212231      41.894268   
2018-03-21 17:31:00             11  ...  1153-201803212231      41.953814   

                    START_LONGITUDE  END_LATITUDE  END_LONGITUDE  \
TIME                                                               
2018-03-21 17:31:00      -87.744434     41.836747     -87.743932   
2018-03-21 17:31:00      -87.744985     41.851245     -87.744434   
2018-03-21 17:31:00      -87.804549     41.894268     -87.805101   
2018-03-21 17:31:00      -87.805101     41.908856     -87.805554   
2018-03-21 17:31:00      -87.807150     41.968344     -87.806982   

                                           START_LOCATION  \
TIME                                                        
2018-03-21 17:31:00  POINT (-87.7444337191 41.8512451897)   
2018-03-21 17:31:00  POINT (-87.7449852043 41.8659627382)   
2018-03-21 17:31:00  POINT (-87.8045488066 41.8796992839)   
2018-03-21 17:31:00  POINT (-87.8051007941 41.8942683013)   
2018-03-21 17:31:00  POINT (-87.8071497455 41.9538138239)   

                                             END_LOCATION Community Areas  \
TIME                                                                        
2018-03-21 17:31:00  POINT (-87.7439318058 41.8367473974)             NaN   
2018-03-21 17:31:00  POINT (-87.7444337191 41.8512451897)            26.0   
2018-03-21 17:31:00  POINT (-87.8051007941 41.8942683013)             NaN   
2018-03-21 17:31:00  POINT (-87.8055536529 41.9088560337)             NaN   
2018-03-21 17:31:00  POINT (-87.8069823878 41.9683436725)            17.0   

                    Zip Codes  Wards  
TIME                                  
2018-03-21 17:31:00      4458    NaN  
2018-03-21 17:31:00     22216    7.0  
2018-03-21 17:31:00     26615    NaN  
2018-03-21 17:31:00     26615    NaN  
2018-03-21 17:31:00     22254   19.0  

[5 rows x 22 columns]

In [37]:
df['SPEED'].unique()

array([23, 20, 14, 36, 35, 27, 18, 17, 12,  8, 19, 13, 24, 26, 25, -1, 21,
       16, 22,  7,  4, 11, 28, 15, 30, 10, 32, 29, 33, 34, 39, 50, 38, 31,
       52,  9,  3,  5, 51, 43, 44, 47, 41, 49, 54, 53, 55, 40, 46, 37,  6,
       45, 48, 42,  0, 56,  2,  1, 57], dtype=int64)